### ISSUE TITLE
A user requested to have this run on aarch64

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pysoundfile-feedstock#6]
xref: 
https://github.com/Archiconda/build-tools/commit/3dfab94028e87812e9efa6f0dc215460de8e26cc

cc @conda-forge-arm

@gerardgilliland

**Comment by hmaarrfk** [comment]
@conda-forge/arm-arch, we can probably add this to the migration queue.

**Comment by scopatz** [comment]
yeah, that would be good to have. It has some difficult deps

**Comment by wolfv** [comment]
This should work as libsndfile is available on all platforms.
