### ISSUE TITLE
dependency problems for noarch

### ISSUE THREAD

**Issue by bmcfee** [conda-forge/pysoundfile-feedstock#9]
It appears that the pysoundfile package currently does not install properly on windows platforms.  Quoting from this [comment](https://github.com/conda-forge/librosa-feedstock/issues/24#issuecomment-575383944) on the librosa feedstock:

> The problem is in the pysoundfile package. It depends on libsndfile, but that package does not exist. All we have on windows is a different beast, m2w64-libsndfile. This is a different name because it is from a completely different compiler stack (mingw as opposed to visual studio). This kind of messes up the ability to make pysoundfile noarch, because selectors are not allowed (they take effect at build time, not run time). There could be a scheme to unify these using metapackages, though.

followed by [this comment](https://github.com/conda-forge/librosa-feedstock/issues/24#issuecomment-575393511)
> Simplest is to just remove noarch from pysoundfile, add the selectors, bump the build number. I would then add an issue on the pysoundfile repo and also put a comment in the recipe as to why the selector is needed, and note the possibility of a metapackage to get noarch back.
> 
> There might also be something we can do to help the bot understand that the recipe can't be noarch, but the selectors should be enough.

I'll cop to being out of my depth on how exactly to implement this, but I wanted to put it on the soundfile package maintainers' radar, since it is causing troubles downstream.

**Comment by scopatz** [comment]
It is much easier to maintain a noarch package, so I am inclined to keep this as it is. The proper solution is to get a libsndfile working for windows. Thanks for letting us know!

**Comment by wolfv** [comment]
We have a proper libsndfile for Windows now, but this library still doesn't work fully on Windows due to a peculiarity whne building the noarch pacakge. #12 fixes this.

**Comment by wolfv** [comment]
fixed.
